# Generated by Django 5.2.6 on 2025-10-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('passwordhash', models.CharField(max_length=100)),
                ('parking_pass', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Res', 'Resident')], max_length=5, null=True)),
            ],
        ),
    ]
