# Generated by Django 5.2.6 on 2025-10-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parking_pass',
        ),
    ]
