# Generated by Django 5.2.6 on 2025-11-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_ada_sort',
            field=models.BooleanField(default=False, help_text='Whether to sort parking garages by ADA spaces by default'),
        ),
    ]
