# Generated by Django 5.2.6 on 2025-10-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0002_remove_user_parking_pass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwordhash',
            new_name='password',
        ),
    ]
