# Generated by Django 5.2.6 on 2025-10-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0003_rename_passwordhash_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parking_pass',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Res', 'Resident')], max_length=5, null=True),
        ),
    ]
