# Generated by Django 5.2.6 on 2025-10-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0004_user_parking_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='testname', max_length=45),
            preserve_default=False,
        ),
    ]
