# Generated by Django 5.2.6 on 2025-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0005_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
