# Generated by Django 5.2.6 on 2025-10-24 21:04

import django.contrib.postgres.fields
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0006_user_notification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('parking_passes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Res', 'Resident')], max_length=10), size=None)),
                ('special_lot', models.CharField(blank=True, choices=[('FB', 'Football'), ('BB', 'Basketball')], max_length=10, null=True)),
                ('cameras', models.CharField(max_length=200)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
