# Generated by Django 5.2.6 on 2025-10-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0006_user_notification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_origin',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]


