# Generated by Django 5.2.6 on 2025-10-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0007_user_default_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lot_code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='lotevent',
            index=models.Index(fields=['lot_code', 'start_time'], name='boiler_par_lot_cod_0a2a6b_idx'),
        ),
    ]


