# Generated by Django 5.2.6 on 2025-10-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0007_parkinglot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='location',
        ),
    ]
