# Generated by Django 5.2.8 on 2025-11-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boiler_park_backend", "0008_lotevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("pass_sale", "Parking Pass Sale"),
                            ("lot_closure", "Lot Closure Alert"),
                            ("permit_expiring", "Permit Expiring"),
                            ("event_closure", "Event Day Closure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="lotevent",
            new_name="boiler_park_lot_cod_391bf4_idx",
            old_name="boiler_par_lot_cod_0a2a6b_idx",
        ),
        migrations.AlterField(
            model_name="lotevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="boiler_park_backend.user",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["user", "sent_at"], name="boiler_park_user_id_e8e013_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["notification_type", "sent_at"],
                name="boiler_park_notific_c220b6_idx",
            ),
        ),
    ]
