# Generated by Django 5.2.8 on 2025-11-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boiler_park_backend", "0009_notificationlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="closure_notifications_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
