# Generated by Django 5.2.7 on 2025-11-07 06:50

import django.contrib.postgres.fields
import django.db.models.deletion
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0010_user_closure_notifications_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "dates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(), size=None
                    ),
                ),
                (
                    "location",
                    location_field.models.plain.PlainLocationField(max_length=63),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boiler_park_backend.user",
                    ),
                ),
            ],
        ),
    ]
