# Generated by Django 5.2.7 on 2025-11-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0011_calendarevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="boiler_park_backend.user",
            ),
        ),
    ]
