# Generated by Django 5.2.7 on 2025-11-07 07:10

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0012_alter_calendarevent_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=models.TimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="location",
            field=location_field.models.plain.PlainLocationField(max_length=200),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start_time",
            field=models.TimeField(max_length=200),
        ),
    ]
