# Generated by Django 5.2.7 on 2025-11-07 07:18

import django.contrib.postgres.fields
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0013_alter_calendarevent_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(max_length=1000), size=None
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=models.TimeField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="location",
            field=location_field.models.plain.PlainLocationField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start_time",
            field=models.TimeField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
