# Generated by Django 5.2.7 on 2025-11-18 21:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0014_alter_calendarevent_dates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('paid', models.BooleanField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('parking_passes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Res', 'Residence Hall'), ('Paid', 'Paid')], max_length=100), size=None)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
