# Generated by Django 5.2.7 on 2025-11-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0014_alter_calendarevent_dates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_ada_sort",
            field=models.IntegerField(null=True),
        ),
    ]
