# Generated by Django 5.2.7 on 2025-11-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0015_user_default_ada_sort"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="default_ada_sort",
        ),
    ]
