# Generated by Django 5.2.7 on 2025-11-18 22:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0015_parkinglot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='parking_passes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('SG', 'SG'), ('Res', 'Residence Hall'), ('Paid', 'Paid')], max_length=100), size=None),
        ),
    ]
