# Generated by Django 5.2.7 on 2025-11-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0016_alter_parkinglot_parking_passes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
