# Generated by Django 5.2.7 on 2025-11-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0016_remove_user_default_ada_sort"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="events",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="favorite_lots",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="lot_ratings",
            field=models.JSONField(default=dict),
        ),
    ]
