# Generated by Django 5.2.7 on 2025-11-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0017_user_events_user_favorite_lots_user_lot_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lot_ratings",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
