# Generated by Django 5.2.7 on 2025-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0017_alter_parkinglot_paid_alter_parkinglot_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='num_of_ratings',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
