# Generated by Django 5.2.7 on 2025-11-21 15:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0018_parkinglot_num_of_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_lots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
