# Generated by Django 5.2.7 on 2025-11-24 01:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0018_alter_user_lot_ratings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorite_lots",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="lot_ratings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
