# Generated by Django 5.2.7 on 2025-11-21 16:16

import boiler_park_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0019_user_favorite_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lot_ratings',
            field=models.JSONField(default=boiler_park_backend.models.User.empty_rating_json),
        ),
    ]
