# Generated by Django 5.2.7 on 2025-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0020_user_lot_ratings'),
    ]

    operations = [
        # No-op: `events` is already added in
        # 0017_user_events_user_favorite_lots_user_lot_ratings.
        # Keeping this migration preserves the dependency chain (0022 depends on 0021)
        # without attempting to add a duplicate DB column.
    ]
