# Generated by Django 5.2.7 on 2025-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0020_user_lot_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
