# Generated by Django 5.2.7 on 2025-11-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0021_user_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lot_ratings',
            new_name='individual_lot_rating',
        ),
    ]
