# Generated by Django 5.2.7 on 2025-11-21 16:29

import boiler_park_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0022_rename_lot_ratings_user_individual_lot_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='individual_lot_rating',
        ),
        migrations.AddField(
            model_name='user',
            name='lot_ratings',
            field=models.JSONField(default=boiler_park_backend.models.User.empty_rating_json),
        ),
    ]
