# Generated by Django 5.2.7 on 2025-12-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boiler_park_backend', '0023_remove_user_individual_lot_rating_user_lot_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
