# Generated by Django 5.2.7 on 2025-12-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0019_alter_user_favorite_lots_alter_user_lot_ratings"),
        ("boiler_park_backend", "0024_user_other_location"),
    ]

    operations = []
