# Generated by Django 5.2.7 on 2025-12-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boiler_park_backend", "0025_merge_20251203_1737"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPark",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("day_of_week", models.CharField(blank=True, max_length=9, null=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_logs",
                        to="boiler_park_backend.parkinglot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_logs",
                        to="boiler_park_backend.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="boiler_park_user_id_4c3197_idx",
                    ),
                    models.Index(
                        fields=["lot", "timestamp"],
                        name="boiler_park_lot_id_db7526_idx",
                    ),
                    models.Index(
                        fields=["user", "day_of_week"],
                        name="boiler_park_user_id_f147f0_idx",
                    ),
                ],
            },
        ),
    ]
